### ISSUE TITLE
[Bug]: Laravel 10 support?

### ISSUE THREAD

**Issue by beholdr** [iksaku/laravel-swr-cache#1]
### What happened?

When tried to install on Laravel 10 I've got error:

iksaku/laravel-swr-cache 1.0.0 requires illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.

### How to reproduce the bug

Install with Laravel 10

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10

**Comment by iksaku** [comment]
Done! Please test the new release and let me know if something doesn't seem to be right.

https://github.com/iksaku/laravel-swr-cache/releases/tag/1.0.1
